spring:
  config:
    activate:
      on-profile:
        - local
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: H2
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
        default_batch_fetch_size: 500
        format_sql: true